company/urls.py
from django.contrib import admin
from django.urls import path
from staff.views import DepartmentListView, DepartmentDetailView, CreateEmployeeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('departments/', DepartmentListView.as_view(), name='departments'),
    path('department/<pk>/', DepartmentDetailView.as_view(), name='department-detail'),
    path('add-employee/', CreateEmployeeView.as_view(), name='add-employee')
]

staff/models.py
from django.db import models


class Employee(models.Model):
    employee_name = models.CharField(max_length=250)
    department = models.ForeignKey('Department', on_delete=models.CASCADE)
    email = models.EmailField(max_length=250, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    picture = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.employee_name


class Department(models.Model):
    department_name = models.CharField(max_length=250)
    manager = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True, blank=True,
        related_name='departments')

    def __str__(self):
        return self.department_name

staff/forms.py
from django.forms import ModelForm
from staff.models import Employee


class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields = ('employee_name', 'department')

staff/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from staff.models import Department
from staff.forms import EmployeeForm


class DepartmentListView(ListView):

    model = Department


class DepartmentDetailView(DetailView):

    model = Department


class CreateEmployeeView(CreateView):
	
    template_name = 'staff/create_employee.html'
    form_class = EmployeeForm
    success_url = '/departments/'

staff/templates/staff/create_employee.html
<h1>Add Employee</h1>
<form method="post" action="">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Add"/>
</form>

staff/templates/staff/department_detail.html
<h1>{{ object.department_name }} {% if object.manager %} - {{object.manager}}{% endif %}</h1>
<ul>
{% for employee in object.employee_set.all %}
  <li>{{employee.employee_name}}</li>
{% empty %}
    <li>No Employees</li>
{% endfor %}
</ul>
<a href="{% url 'departments' %}">Back</a>

staff/templates/staff/department_list.html
<h1>Departments</h1>
<ul>
{% for department in object_list %}
  <li><a href="{% url 'department-detail' department.id %}">{{department}}</a></li>
{% empty %}
    <li>No Depatrments</li>
{% endfor %}
</ul>